# Generated by Django 4.2 on 2023-04-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('tickets', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='events.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventdate',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='events_eventdate_end_must_be_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='eventdate',
            constraint=models.CheckConstraint(check=models.Q(('start__gt', django.db.models.functions.datetime.TruncDay(django.db.models.functions.datetime.Now()))), name='events_eventdate_start_must_be_gte_today'),
        ),
    ]
