# Generated by Django 4.2 on 2023-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('tickets', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
