# Generated by Django 4.2 on 2023-04-30 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventdate_events_eventdate_start_must_be_gte_today_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventdate',
            name='events_eventdate_end_must_be_gte_start',
        ),
        migrations.RemoveConstraint(
            model_name='eventdate',
            name='events_eventdate_start_must_be_gte_today',
        ),
        migrations.AddConstraint(
            model_name='eventdate',
            constraint=models.CheckConstraint(check=models.Q(('end__gte', models.F('start'))), name='events_eventdate_end_must_be_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='eventdate',
            constraint=models.CheckConstraint(check=models.Q(('start__gte', datetime.datetime(2023, 4, 30, 10, 35, 50, 930982, tzinfo=datetime.timezone.utc))), name='events_eventdate_start_must_be_gte_today'),
        ),
    ]
