# Generated by Django 4.2 on 2023-04-12 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='end',
            field=models.DateField(default=datetime.datetime(2023, 4, 12, 17, 44, 13, 279582)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='start',
            field=models.DateField(),
        ),
    ]
