# Generated by Django 4.2 on 2023-04-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventdate_end_alter_eventdate_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='events.event'),
        ),
    ]
